export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const SUCCESS_CALLBACK = 'SUCCESS_CALLBACK';
export const ERROR_CALLBACK = 'ERROR_CALLBACK';
